### ISSUE TITLE
Agent安装失败

### ISSUE THREAD

**Issue by 0Joker** [ysrc/yulong-hids#76]
用过Centos7 也用过Ubuntu18.04都是一样的错误

root@ubuntu:/tmp# /tmp/daemon -install -netloc ××××
2020/02/10 15:46:30 Download Agent
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x6a0ac8]

goroutine 1 [running]:
yulong-hids/daemon/install.downFile(0xc420066120, 0x57, 0xc4200145e0, 0x16, 0x0, 0x0)
	/usr/local/go/src/yulong-hids/daemon/install/lib.go:36 +0x1d8
yulong-hids/daemon/install.DownAgent(0x7ffcbbc677c0, 0xd, 0xc4200145e0, 0x16, 0x78ed7a, 0x2, 0x16, 0x0)
	/usr/local/go/src/yulong-hids/daemon/install/lib.go:89 +0x1de
yulong-hids/daemon/install.Agent(0x7ffcbbc677c0, 0xd, 0x796f18, 0x11, 0x78ed7a, 0x2, 0x0, 0xc42016a0a8)
	/usr/local/go/src/yulong-hids/daemon/install/agent_linux.go:13 +0xf7
main.main()
	/usr/local/go/src/yulong-hids/daemon/daemon.go:109 +0x68f

**Comment by amadeus2** [comment]
我也是这样，现在解决了吗？

**Comment by medasz** [comment]
手动上传agent,daemon,data.zip并运行/path/to/yuor/daemon -install -netloc ××××试试
